security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        database_users:
            entity:
                class: App:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|scss|images|js)/
            security: false

        main:
            anonymous: true
            pattern: ^/
            guard:
                authenticator:
                    - App\Security\LoginAuthenticator

                entry_point: App\Security\LoginAuthenticator

            logout:
                path: security_logout
                target: /

    role_hierarchy:
        ROLE_ADMIN: ROLE_ADMIN

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auteur, roles: ROLE_AUTER }
        - { path: ^/lecteur,  roles: ROLE_USER }
