<?php

namespace App\Controller;


use App\Entity\Editeur;
use App\Entity\ImageAdmin;
use App\Entity\InterView;
use App\Entity\Question;
use App\Form\ImageAdminType;
use App\Form\QuestionType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class FrontController extends AbstractController
{


    /**
     * @Route("/admin/editeur/{id}", name="editeur_show", methods={"GET", "POST"})
     */
    public function showE(Editeur $editeur): Response
    {
        return $this->render('pages/interview-editors.html.twig', [
            'editeur' => $editeur,
        ]);
    }
    /**
     * @Route("/admin/editeur/{slug}/question/new", name="questionE_new", methods={"POST"})
     */
    public function newQuestionE(Request $request, Editeur $editeur): Response
    {
        $question = new Question();
        $form = $this->createForm(QuestionType::class, $question);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $editeur->addQuestions($question);


            $em->persist($question);
            $em->flush();
        } return $this->redirectToRoute('editeur_show', ['slug' => $editeur->getSlug()]);
    }

    /**
     * @Route("/admin/editeur/{slug}/imageE/new", name="imageE_new", methods={"POST"})
     */
    public function newImageE(Request $request, Editeur $editeur): Response
    {
        $editeur->addImage(new ImageAdmin());
        $form = $this->createForm(ImageAdminType::class, $editeur);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

                if ($file = $editeur->getFile()) {
                    $fileName = $this->generateUniqueFileName();
                    $editeur->setAlt($fileName);
                    $file->move($this->getParameter('imagesAdmin_directory'), $fileName);
                }


            $em = $this->getDoctrine()->getManager();
            $editeur->addImage($editeur);
            $em->persist($editeur);
            $em->flush();
        } return $this->redirectToRoute('editeur_show', ['slug' => $editeur->getSlug()]);
    }
    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    /**
     * @ParamConverter()
     */
    public function imageEForm(Editeur $editeur): Response
    {
        $form = $this->createForm(ImageAdminType::class);

        return $this->render('admin/_imageAdmin_form.html.twig', [
            'form' => $form->createView(),
            'editeur' => $editeur,
        ]);
    }
    /**
     * @ParamConverter()
     */
    public function questioneForm(Editeur $editeur): Response
    {
        $form = $this->createForm(QuestionType::class);

        return $this->render('admin/_question_form.html.twig', [
            'form' => $form->createView(),
            'editeur' => $editeur,
        ]);
    }


    /**
     * @Route("interView/{slug}", name="interView_show", methods={"GET", "POST"})
     */
    public function showI(InterView $interView): Response
    {
        return $this->render('pages/interview-editors.html.twig', [
            'interView' => $interView,
        ]);
    }
    /**
     * @Route("/admin/interView/{slug}/question/new", name="questionI_new", methods={"POST"})
     */
    public function newQuestionI(Request $request, InterView $interView): Response
    {
        $question = new Question();
        $form = $this->createForm(QuestionType::class, $question);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $interView->addQuestions($question);


            $em->persist($question);
            $em->flush();
        } return $this->redirectToRoute('interView_show', ['slug' => $interView->getSlug()]);
    }

    /**
     * @ParamConverter()
     */
    public function questioniForm(Editeur $interView): Response
    {
        $form = $this->createForm(QuestionType::class);

        return $this->render('admin/_question_form.html.twig', [
            'form' => $form->createView(),
            'interView' => $interView,
        ]);
    }

}
